### ISSUE TITLE
Add License and Package JSON file

### ISSUE THREAD

**Issue by brutalhonesty** [Clarifai/clarifai-nodejs#2]
Would be great to get this package into [NPM](https://www.npmjs.com/).

Could you please create a package.json file for this using ```npm init``` as well as adding a LICENSE file and noting it within the package.json file as well as your README?

Thanks! :)

**Comment by Carter-Wayblazer** [comment]
Agreed, we would like that, too.

**Comment by dankantor** [comment]
We are now on NPM! https://www.npmjs.com/package/clarifai
