### ISSUE TITLE
Why are there two js clients for clarifai?

### ISSUE THREAD

**Issue by abdulhannanali** [Clarifai/clarifai-nodejs#5]
I was trying out the clarifai on node.js and discovered two api clients this one and [clarifai-javascript](https://github.com/Clarifai/clarifai-javascript). 

Is this client needed or does it serve a specific purpose which clarifai-javascript doesn't? Moreover, clarifai-javascript is more up to date. If this is just the old one, why don't you deprecate it?

**Comment by dankantor** [comment]
Yes please use https://github.com/Clarifai/clarifai-javascript. We will remove this one. Sorry for the confusion.

**Comment by abdulhannanali** [comment]
Thanks for the quick response @dankantor
